component: http
name: mixtream
stage: prod

inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - 'node_modules/**'

  faas:
    runtime: Nodejs16.13
    memorySize: 1024
    framework: nextjs
    name: ${name}
    layers:
      - name: ${output:${stage}:${app}:${name}-layer.name}
        version: ${output:${stage}:${app}:${name}-layer.version}

  apigw:
    protocols:
      - http
      - https
    customDomains:
      - domain: mixtream.zhili-edu.com
        isForcedHttps: true
        certId: v9EhNZDO
        customMap: true
        isDefaultMapping: false
        pathMap:
          - path: /
            environment: release
        protocols:
          - http
          - https
